#pragma once

// Disable a bunch of unneeded crap in WinAPI (on top of WIN32_LEAN_AND_MEAN)
#ifdef _WIN32
#define NOMINMAX
#define NOGDI
#define NOKERNEL
#define NONLS
#define NOMEMMGR
#define NOGDICAPMASKS
#define NOVIRTUALKEYCODES
#define NOWINMESSAGES
#define NOWINSTYLES
#define NOMETAFILE
#define NOSCROLL
#define NOTEXTMETRIC
#define NOCOMM
#define NOKANJI
#define NOHELP
#define NOPROFILER
#define NODEFERWINDOWPOS
#define NOMCX
#define NOMENUS
#define NOICONS
#define NOKEYSTATES
#define NOSYSCOMMANDS
#define NORASTEROPS
#define NOSHOWWINDOW
#define OEMRESOURCE
#define NOATOM
#define NODRAWTEXT
#define NOCOLOR
#define NOCTLMGR
#define NOMSG
#define NOOPENFILE
#define NOSERVICE
#define NOSOUND
#define NOWH
#define NOWINOFFSETS
#endif
